server:
  port: 9292

station:

  name: station1
  id: 0

  resources:
    PHT_RESOURCE_FHIR_DSTU3: http://142.93.105.33:8080/baseDstu3
    PHT_FILE_DOWNLOAD_SERVICE: http://file_download_service_0

  registry:
    uri: http://134.2.9.126:5000
    namespace: namespace
    username: lukas
    password: testpass
