server:
  port: 9292

station:

  name: station0
  id: 0

  resources:
    PHT_RESOURCE_FHIR_DSTU3: http://142.93.105.33:8080/baseDstu3
    PHT_FILE_DOWNLOAD_SERVICE: http://file_download_service_0:5000

  docker:
    networkId: 3247ad7c77141254964be87e846ea09084e3710e7b779cffc298ee4e961834d0

  registry:
    uri: http://193.196.20.100:5000
    namespace: namespace
    username: admin
    password: adminpass
